[workspace]
resolver = "2"

members = [
  'modality-network-consensus'
, 'modal-datastore'
, 'modality-network-devnet'
, 'modal-mining'
, 'modality-network-node'
, 'modality-network-sequencing'
, "modality-utils"
, "modality"
, "modality-lang"
, "modal"
, "modal-networks"]

[profile.release]
strip = true
lto = true





